name: Docker CentOS Image Build

on:
  push:
    branches:
      - 'main'
      - 'te*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v2
      # extract branch name
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(branchname=${GITHUB_REF#refs/heads/};echo ${branchname,,})"
        id: extract_branch
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # extract branch name on pull request
      - name: Extract branch name on Pull Request
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(branchname=${GITHUB_REF};echo ${branchname,,})"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - name: My step
        run: echo ${SHORT_SHA}
      - name: Download Dependencies
        run: |
          curl -o OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz https://corretto.aws/downloads/resources/15.0.2.7.1/amazon-corretto-15.0.2.7.1-linux-x64.tar.gz
          sleep 5s
      - name: Extract JDK
        uses: a7ul/tar-action@v1.1.0
        id: extract1
        with:
          command: x
          files: OpenJDK8U-jdk_x64_linux_hotspot_8u362b09.tar.gz
      - name: Build and push CentOS image
        run: |
          docker build . -t vsumanth/centos:${BRANCH_NAME}-${SHORT_SHA} -f Dockerfile_centos_empty
          docker push vsumanth/centos:${BRANCH_NAME}-${SHORT_SHA}
